name: Build, Test, and Coverage

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  TestAndCoverage:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        python:
          - {version: "3.7", envname: "py37"}
          - {version: "3.8", envname: "py38"}
          - {version: "3.9", envname: "py39"}
          - {version: "3.10", envname: "py310"}

    name: Test and Coverage (os=${{ matrix.os }}, py=${{ matrix.python.version }})
    runs-on: ${{ matrix.os }}
    env:
      TOX_PARALLEL_NO_SPINNER: 1
      TOX_REPORT_PREFIX: ${{ matrix.os }}_${{ matrix.python.envname }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python Version ${{ matrix.python.version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python.version }}
      - name: Setup Environment
        # we setup the dev environment anyway
        run: |
          pip install --upgrade pip
          pip install .[dev]
      - name: Run all tests
        run: |
          tox -p -v
      - name: Generate Coverage Reports
        run: |
          coverage combine
          coverage xml -o coverage_report.xml
      - name: Publish Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure() # always run even if the previous step fails
        with:
          name: Unit Tests (os=${{ matrix.os }}, py=${{ matrix.python.version }})
          path: '**/*_unit_test_result.xml'
          reporter: java-junit
      - name: Publish Code Coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          files: "coverage_report.xml"
          fail_ci_if_error: true
