name: Build, Test, and Coverage

on:
  push

jobs:
  BuildAndTest:

    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.7
        uses: actions/setup-python@v3
        with:
          python-version: '3.7'
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python3.9 -m pip install --upgrade pip
          python3.9 -m pip install .[dev]
      - name: Run Test With Coverage
        run: |
          TOX_PARALLEL_NO_SPINNER=1 python3.9 -m tox --parallel --verbose
      - name: Publish Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure() # always run even if the previous step fails
        with:
          name: Unit Tests
          path: '**/*_unit_test_result.xml'
          reporter: java-junit
      - name: Publish Code Coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          files: "*_coverage_report.xml"
          fail_ci_if_error: true
      - name: Docs
        run: sphinx-build -W docs dist/docs
