name: Build, Test, and Coverage

on:
  push

jobs:
  Build_And_Test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
      - name: Run test with coverage
        run: >
          pytest --cov pyetta --cov-report xml:coverage_report.xml
          --junitxml=unit_test_result.xml
      - name: Publish Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure() # always run even if the previous step fails
        with:
          name: Unit Tests
          path: '**/unit_test_result.xml'
          reporter: java-junit
      - name: Publish Code Coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          files: coverage_report.xml
          fail_ci_if_error: true
