name: Build, Test, and Coverage

on:
  push

jobs:
  BuildAndTest:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    name: Build and Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.7
        uses: actions/setup-python@v3
        with:
          python-version: '3.7'
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install dependencies (using latest python)
        run: |
          python --version
          pip --version
          pip install --upgrade pip
          pip install .[dev]
      - name: Run Test With Coverage
        run: |
          TOX_PARALLEL_NO_SPINNER=1 tox -p
      - name: Publish Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure() # always run even if the previous step fails
        with:
          name: Unit Tests
          path: '**/*_unit_test_result.xml'
          reporter: java-junit
      - name: Publish Code Coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          files: "*_coverage_report.xml"
          fail_ci_if_error: true
      - name: Docs
        run: sphinx-build -W docs dist/docs
